name: Build and Deploy to Azure Container Apps

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: chukuregistry
  CONTAINER_APP_NAME: scalable-app
  RESOURCE_GROUP: scalable
  IMAGE_NAME: chukuscalable
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    # - name: Deploy to Azure Container Apps
    #   uses: azure/container-apps-deploy-action@v1
    #   with:
    #     containerAppName: ${{ env.CONTAINER_APP_NAME }}
    #     resourceGroup: ${{ env.RESOURCE_GROUP }}
    #     imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
    #     environmentVariables: |
    #       DJANGO_SETTINGS_MODULE=your_project.settings
    #       SECRET_KEY=secretRef:django-secret-key
    #       ALLOWED_HOSTS=*.azurecontainerapps.io